### ISSUE TITLE
Build folder is never found

### ISSUE THREAD

**Issue by devmanusanram** [SamKirkland/FTP-Deploy-Action-Example-React#5]
Ran into some issues a couple of hours ago. I'm trying to upload a React App via FTP but when I try to find the `build` folder, it always throws the following error:

`find: ‘build/’: No such file or directory
Error: Process completed with exit code 1.`

Here's my yml file:

```
name: Publish SurCor into website

on:
    push:
        branches: main

jobs:
    ftp-deploy-surcor:
        name: FTP Deploy SurCor
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [16.x, 18.x]

        steps:
            - name: Checkout the repo SurCor
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
  
            - name: Copy prod.env to .env
              run: cp prod.env .env

            - name: Build project
              run:
                npm install --force
                npm run build

            - name: List output files
              run: find build/ -print
            
            - name: FTP Deploy Action
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                server: ${{ secrets.FTP_SERVER }}
                password: ${{ secrets.FTP_PASSWORD }}
                username: ${{ secrets.FTP_USERNAME }}
                dangerous-clean-slate: true
                local-dir: build/
                server-dir: ./public_html/
```
1.- I make use of .env files to run my app
2.- The `server-dir` may be wrong, I'm trying to feed the build content into a cPanel hosted domain.
3.-  I omitted any ignore of build from .gitignore, hence I don't have the folder in my repo and cannot find it as local-dir
