### ISSUE TITLE
Error: Error: ENOENT: no such file or directory, scandir 'build/'

### ISSUE THREAD

**Issue by PedroGomes15** [SamKirkland/FTP-Deploy-Action-Example-React#6]
I tried every way but I always get an error with the build folder path, any solution? Could it be the version?

this is my worlflow script, my package.json has the default function, and the list command is listing the files correctly

```
on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🛠️ Build website
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 🎈 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Execute o comando de build
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
    
      - name: List output files
        run: find build/ -print
      
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: build/
          

```
          
**Error: Error: ENOENT: no such file or directory, scandir 'build/'**
